### ISSUE TITLE
[QUESTION] How to see all methods?

### ISSUE THREAD

**Issue by renzmann** [wesselb/plum#12]
If I define a few dispatched methods:
```
@dispatch
def foo(x: str):
    print("String")


@dispatch
def foo(x: int):
    print("Int")


@dispatch
def foo(x: float):
    print("Float")


foo  # <function <function foo at 0x7f897111ca60> with 3 method(s)>
```

It's clearly telling me that there's three methods for `foo`, but not what types it *can* dispatch on. What I think would be nice is like in Julia's help system `?`, we can search for the method name and get a list of the concrete implementations. Is something like that possible for  `plum` too?

**Comment by wesselb** [comment]
Hey @renzmann,

You're right that there is currently no documented way to get a list of all available methods.

At the moment, this is possible:

```python
>>> foo.methods
{}

>>> foo(1)
Int

>>> foo.methods
{Signature(builtins.str): (<function __main__.foo(x:str)>, builtins.object),
 Signature(builtins.int): (<function __main__.foo(x:int)>, builtins.object),
 Signature(builtins.float): (<function __main__.foo(x:float)>,
  builtins.object)}
```

The dictionary has as keys method signatures and as values tuples of the implementation and return value.

Note that the dictionary `foo.methods` is populated lazily, which is why you must run `foo(some_argument)` to see the available methods.

For class methods, this unfortunately currently breaks (`AttributeError: '_BoundFunction' object has no attribute 'methods'`), but I'll make it a TODO to fix that up and add an entry to the README.

**Comment by wesselb** [comment]
@renzmann, in `v1.3.0`, the attributes `methods` and `precedences` are now part of the API and can be safely used:

```python
from plum import dispatch

@dispatch
def foo(x: str):
    print("String")


@dispatch
def foo(x: int):
    print("Int")


@dispatch
def foo(x: float):
    print("Float")
```

```python
>>> foo.methods
{Signature(builtins.str): (<function __main__.foo(x:str)>, builtins.object),
 Signature(builtins.int): (<function __main__.foo(x:int)>, builtins.object),
 Signature(builtins.float): (<function __main__.foo(x:float)>,
  builtins.object)}

>>> foo.precedences
{Signature(builtins.str): 0,
 Signature(builtins.int): 0,
 Signature(builtins.float): 0}
```

I've added a few lines to the README.
