### ISSUE TITLE
Non-supported typings as ReturnType.

### ISSUE THREAD

**Issue by pdeibert** [wesselb/plum#21]
There seems to be an issue with (yet) non-supported typings, even if the type in question is only a return type.

With the latest version (via pip) and python 3.8.5, this example code
```
from plum import dispatch
from typing import Dict

@dispatch
def foo(x: int, y: str) -> Dict[int, str]:
    return {x: y}

print(foo(1, "1"))
```
yields the following error:
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    def foo(x: int, y: str) -> Dict[int, str]:
  File "/home/bob/dev_env/lib/python3.8/site-packages/plum/dispatcher.py", line 38, in __call__
    signature, return_type = extract_signature(method)
  File "plum/function.py", line 81, in plum.function.extract_signature
  File "/home/bob/dev_env/lib/python3.8/site-packages/plum/type.py", line 353, in ptype
    f'There is currently no support for "typing.{obj.__name__}". '
  File "/home/bob/anaconda3/lib/python3.8/typing.py", line 760, in __getattr__
    raise AttributeError(attr)
AttributeError: __name__
```

Is this expected behavior or is there any way to resolve this?

**Comment by wesselb** [comment]
Hey @pdeibert,

Currently, the `Dict` type from typing is not supported, but it should be relatively easy to add support for it.

Moreover, unfortunately the error message `There is currently no support for "typing.{obj.__name__}". (...)`, which would've been descriptive, raised an exception, because `__name__` is not available. That's very sloppy on my part.

I'm currently on holidays, so I won't be able to add support for `Dict` and fix the error message right now, but I will be able to fix those when I get back.

**Comment by wesselb** [comment]
I've added support for `typing.Dict` in the latest release `v1.5.0`. Your snippet should now work:

```python
from plum import dispatch
from typing import Dict

@dispatch
def foo(x: int, y) -> Dict[int, str]:
    return {x: y}
```

```python
>>> foo(1, "1")
{1: '1'}

>>> foo(1, 1)
TypeError: Cannot convert a "Dict[builtins.int, builtins.int]" to a "Dict[builtins.int, builtins.str]".
```
